export const login = [
  {
    name: '__Secure-3PSIDCC',
    value: 'AFvIBn8BxsWqyhBq7-51THExnJOWsjdyiZxMEVCiF-7cIcZ-vAOZT7cuF4Fkjj9ej1YM8csp',
    domain: '.google.com',
    path: '/',
    expires: 1712679573.035555,
    size: 88,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PSIDCC',
    value: 'AFvIBn-QJAAm81CmHXlIaYnawhe-o9ogRd3kIuP7j9NVsstXq8qCaULZxLAANElp449ZKZhvzw',
    domain: '.google.com',
    path: '/',
    expires: 1712679573.035463,
    size: 90,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SIDCC',
    value: 'AFvIBn-ZeKfKposAM1AmajgnfqNvZ1KLo5oKLW7ZbRvpt5pK0MIfBg77vAnAyKI5PYfkYPiy',
    domain: '.google.com',
    path: '/',
    expires: 1712679573.035308,
    size: 77,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-3PAPISID',
    value: 'yjF2p9c02qRVadiB/Ah9hTL4jRlvVP-02r',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.362008,
    size: 51,
    httpOnly: false,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SAPISID',
    value: 'yjF2p9c02qRVadiB/Ah9hTL4jRlvVP-02r',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361894,
    size: 41,
    httpOnly: false,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'APISID',
    value: 'Sx6Ul53lwOgWRB_K/AZgBSbT2ilw5SaBui',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361844,
    size: 40,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SSID',
    value: 'A0hy4jVtooqGNEzjt',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361797,
    size: 21,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-3PSID',
    value: 'VAhWEnO25q3egVVmdkxMGvRiVwVbTntQzxNr747yKyoNk3Ozqikk9PEJ9yTr2pMv_8Yn0A.',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361534,
    size: 85,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PSID',
    value: 'VAhWEnO25q3egVVmdkxMGvRiVwVbTntQzxNr747yKyoNk3OzdGFa7hMFMb-8zNPuXlGBAQ.',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361478,
    size: 85,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: true,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SID',
    value: 'VAhWEnO25q3egVVmdkxMGvRiVwVbTntQzxNr747yKyoNk3Ozt9Wjg4Wg3Cwz8-Jm7Oqafg.',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361418,
    size: 74,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PAPISID',
    value: 'yjF2p9c02qRVadiB/Ah9hTL4jRlvVP-02r',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361956,
    size: 51,
    httpOnly: false,
    secure: true,
    session: false,
    sameParty: true,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'HSID',
    value: 'Aht7-aSX4JXEK4u7o',
    domain: '.google.com',
    path: '/',
    expires: 1715703570.361745,
    size: 21,
    httpOnly: true,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'NID',
    value: '511=QpXLgEB499KamxLCa8DmGAWDxBKecYtjQG8yX0SHpA_QVGxEpur3tTH29akhPCyIobwnHIk42WaCSGqG4YSRacbCjR4okPpV1E7TeOF5dR4bXBpOc9hB1kqXwzCBhLTf_nMqyFGGUc5kP69If9yp3lc2p8_B9q2-dfI2VBLt1KuDCPn8r848K63v7Xj_p5Xl-aMEOnCe4EVtKGcovqrTV5gwywS1TsqH',
    domain: '.google.com',
    path: '/',
    expires: 1696954770.361325,
    size: 231,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  }
]