export const login = [
  {
    name: '__Secure-3PSIDCC',
    value: 'APoG2W-Ynn10kP524LZf5R0jxT6fwqMVPnluNwx9bY5dFojjNAkNrmnGGgkVF4dk4qER3H0YgQ',
    domain: '.google.com',
    path: '/',
    expires: 1725376270.41978,
    size: 90,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PSIDCC',
    value: 'APoG2W_vJgEfw0iuXTTBsHIT2-2-59qiSzI6hx0ZshEM-Uqzwj0zyd7tOA374B18Q8ZEe2xseA',
    domain: '.google.com',
    path: '/',
    expires: 1725376270.419695,
    size: 90,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SIDCC',
    value: 'APoG2W_rvvklOB3PeNvmbq81i0ZQuY-aY2DMwk0KZOqpPmqGlByE52i5q42l4eysQFrJPsf3AA',
    domain: '.google.com',
    path: '/',
    expires: 1725376270.419509,
    size: 79,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-3PAPISID',
    value: 'laNPwzkpVE4_3_rM/AKultJ9aZ0WKMHJs3',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461477,
    size: 51,
    httpOnly: false,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SAPISID',
    value: 'laNPwzkpVE4_3_rM/AKultJ9aZ0WKMHJs3',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461366,
    size: 41,
    httpOnly: false,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'APISID',
    value: 'y9BXXMxX3qOKNRUr/AG4Mbr1Hhh2STOT5G',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461313,
    size: 40,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SSID',
    value: 'AH1BADncwUHdtfByG',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461259,
    size: 21,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-3PSID',
    value: 'aghWEoCWLwFIV-oUTQczvjPbqs0r-UzfOt74lx9bcwCYr2uIJeyGwELEN2rsNFRGHrOMMA.',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.460993,
    size: 85,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PSID',
    value: 'aghWEoCWLwFIV-oUTQczvjPbqs0r-UzfOt74lx9bcwCYr2uI2v-CMnfcrUPSO04DvnBl9Q.',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.460937,
    size: 85,
    httpOnly: true,
    secure: true,
    session: false,
    sameParty: true,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'SID',
    value: 'aghWEoCWLwFIV-oUTQczvjPbqs0r-UzfOt74lx9bcwCYr2uISZlUNlM6hzHOjngfn1ExUg.',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.460876,
    size: 74,
    httpOnly: false,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: '__Secure-1PAPISID',
    value: 'laNPwzkpVE4_3_rM/AKultJ9aZ0WKMHJs3',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461423,
    size: 51,
    httpOnly: false,
    secure: true,
    session: false,
    sameParty: true,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'HSID',
    value: 'Abp-z8foje00VWQgd',
    domain: '.google.com',
    path: '/',
    expires: 1728400268.461207,
    size: 21,
    httpOnly: true,
    secure: false,
    session: false,
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  },
  {
    name: 'NID',
    value: '511=PAcWbLUkHZKFTsOpII6vyNBcNnI5pvcpifscJaUgscvMG_-1JWgU0xHrCnrBUyb7F-YmwdNeGIFmHXsK80vMEKc6JC-b0TGe_66eT_PyM3Yt9ccPuxUnD3-5m8RLT7lfj5l5kvW2_wipJCZhNQ20cYII_GizZHF1VpziDuAS-RulLNjsCYjEazjCZT1IUWw74Mpl3A7LPZ-NgydQ9KzXkKx3y5BD7C580RZDOf_aZa6UizlPNp8',
    domain: '.google.com',
    path: '/',
    expires: 1709651462.460801,
    size: 250,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443
  }
]